spring:
  application:
    name: spring-config-server
  profiles:
    active:
    - git
  cloud:
    config:
      server:
        git:
          default-label: Master
          uri:
            https://github.com/isaacfrwk/FrwkQuickWaitSpringConfigs
          username: repo_owner_user_name
          password: repo_owner_github_token
          
server:
  port: 8071
  

#Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"
